//
//  bartLookup.swift
//  Should I Run
//
//  Created by Neil Lobo on 7/16/14.
//  Copyright (c) 2014 Should I Run. All rights reserved.
//

var bartLookup : [String : String] = ["12th St. Oakland City Center" : "12th",
    "16th St. Mission":"16th",
    "19th St. Oakland":"19th",
    "24th St. Mission":"24th",
    "Ashby":"ashb",
    "Balboa Park":"balb",
    "Bay Fair":"bayf",
    "Castro Valley":"cast",
    "Civic Center/UN Plaza":"civc",
    "Coliseum/Oakland Airport":"cols",
    "Colma":"colm",
    "Concord":"conc",
    "Daly City":"daly",
    "Downtown Berkeley":"dbrk",
    "Dublin/Pleasanton":"dubl",
    "El Cerrito del Norte":"deln",
    "El Cerrito Plaza":"plza",
    "Embarcadero":"embr",
    "Fremont":"frmt",
    "Fruitvale":"ftvl",
    "Glen Park":"glen",
    "Hayward":"hayw",
    "Lafayette":"lafy",
    "Lake Merritt":"lake",
    "MacArthur":"mcar",
    "Millbrae":"mlbr",
    "Montgomery St.":"mont",
    "North Berkeley":"nbrk",
    "North Concord/Martinez":"ncon",
    "Orinda":"orin",
    "Pittsburg/Bay Point":"pitt",
    "Pleasant Hill":"phil",
    "Powell St.":"powl",
    "Richmond":"rich",
    "Rockridge":"rock",
    "San Bruno":"sbrn",
    "San Francisco Int'l Airport":"sfia",
    "San Leandro":"sanl",
    "South Hayward":"shay",
    "South San Francisco":"ssan",
    "Union City":"ucty",
    "Walnut Creek":"wcrk",
    "West Dublin":"wdub",
    "West Oakland":"woak"
]

var bartLookupReverse : [String : String] = ["12th":"12th St. Oakland City Center",
    "16th":"16th St. Mission",
    "19th":"19th St. Oakland",
    "24th":"24th St. Mission",
    "ashb":"Ashby",
    "balb":"Balboa Park",
    "bayf":"Bay Fair",
    "cast":"Castro Valley",
    "civc":"Civic Center",
    "cols":"Coliseum/Oakland Airport",
    "colm":"Colma",
    "conc":"Concord",
    "daly":"Daly City",
    "dbrk":"Downtown Berkeley",
    "dubl":"Dublin/Pleasanton",
    "deln":"El Cerrito del Norte",
    "plza":"El Cerrito Plaza",
    "embr":"Embarcadero",
    "frmt":"Fremont",
    "ftvl":"Fruitvale",
    "glen":"Glen Park",
    "hayw":"Hayward",
    "lafy":"Lafayette",
    "lake":"Lake Merritt",
    "mcar":"MacArthur",
    "mlbr":"Millbrae",
    "mont":"Montgomery St.",
    "nbrk":"North Berkeley",
    "ncon":"North Concord/Martinez",
    "orin":"Orinda",
    "pitt":"Pittsburg/Bay Point",
    "phil":"Pleasant Hill",
    "powl":"Powell St.",
    "rich":"Richmond",
    "rock":"Rockridge",
    "sbrn":"San Bruno",
    "sfia":"San Francisco Int'l Airport",
    "sanl":"San Leandro",
    "shay":"South Hayward",
    "ssan":"South San Francisco",
    "ucty":"Union City",
    "wcrk":"Walnut Creek",
    "wdub":"West Dublin",
    "woak":"West Oakland" ]